name: Publish to GH Pages
on:
  push:
    branches:
      - master
jobs:
  build:
    permissions:
      contents: write
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - uses: browser-actions/setup-chrome@v1
    - run: |
        echo "chromePath=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV
        jq --arg chromePath "${{ steps.setup-chrome.outputs.chrome-path }}" '.chromePath = $chromePath' package.json > temp.json && mv temp.json package.json

    - run: npm install
    - run: npm run build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY }}
        BRANCH: gh-pages
        FOLDER: dist
